### PR TITLE
fix(ui): infinite loader on API error

### LINKED ISSUE #234: App sometime gets stuck after API error
## Current behavior

On some occasions, when the API request fails, the application gets seemingly unresponsive, with the loading spinner over the entire page. On the example screen below, it can be seen that a error occurred (red toast in the corner) but nothing can be done.

image

## Expected behavior

The loading overlay should always hide after a server request is complete

### PR DESCRIPTION
**Pull request by martinmaillard**
In some cases, the loader would get stuck when an API error occurred.

The error message would also show up *under* the modal.

Fix #234

### CODE REVIEW

File: ui/src/components/project/TableItem.vue [hunk 1]
```diff
@@ -271,9 +274,12 @@ export default class extends Vue {
...
           const loading = this.$buefy.loading.open({})
-          await this.$store.dispatch('attributes/createReference', { table: this.table, attribute })
-          loading.close()
-          modal.close()
+          try {
+            await this.$store.dispatch('attributes/createReference', { table: this.table, attribute })
+            modal.close()
+          } finally {
+            loading.close()
+          }
```
Comment (tpluscode) [inline ui/src/components/project/TableItem.vue]: Will `Promise` API be a little cleaner then `try..catch`?

```suggestion
          await this.$store.dispatch('attributes/createReference', { table: this.table, attribute })
            .then(() => modal.close())
            .finally(() => loading.close())
```

Comment (martinmaillard) [reply ui/src/components/project/TableItem.vue]: Hum... I guess it's a matter of taste? I generally try not to mix `async/await` with the Promise API if I can avoid it. But can change if you have an argument for it ;)

Comment (tpluscode) [reply ui/src/components/project/TableItem.vue]: No strong arguments. I merely thought it a little more appealing... visually

Comment (martinmaillard) [reply ui/src/components/project/TableItem.vue]: Ok, then I'll keep it that way if you don't mind
