### PR TITLE
fix: must. slugify. table. name

### LINKED ISSUE #257: When creating FactTable with invalid name, table is still assigned to project
If I try to create a FactTable with a weird character in its name, I get a weird parsing error from the API and the table is not created. But it seems that the table is still assigned to the project. If I fix the name and re-submit the form, I get the following error: `Fact table has already been selected.`

### PR DESCRIPTION
**Pull request by tpluscode**
fixes #257

### CODE REVIEW

**Comment by martinmaillard** [comment]
Now I get this error when creating the table:
```
2020-03-26T11:09:06.594Z dataCube:request POST /project/c4760d6c-cc18-4040-854d-ed018ee1796f/tables
2020-03-26T11:09:07.347Z dataCube:request:error Request failed: NotFoundError: at Object.getRepresentation (/.../data-cube-curation/api/lib/read-graphs/table/index.ts:17:11) at processTicksAndRejections (internal/process/task_queues.js:93:5) at /.../data-cube-curation/api/lib/data-cube/table/createDimensionTable.ts:79:13
```

**Comment by tpluscode** [comment]
Yes, notice the failed e2e tests. I'm almost done getting this right

File: api/lib/data-cube/table/index.ts [hunk 1]
```diff
@@ -37,7 +39,10 @@ export const createFactTable = asyncMiddleware(async (req: express.Request, res:
   })
     .commit(projects)
 
-  const tableId = `${projectId}/table/${variables.name.value}`
```
Comment (tpluscode) [inline api/lib/data-cube/table/index.ts]: This was the problematic part I left out which took a shortcut to the fact table id, which was actually incorrect having been  slugified
